import type { Metadata } from 'next';
import { Lexend_Deca } from 'next/font/google';
import './globals.css';

const LexendDeca = Lexend_Deca({
  variable: '--font-lexend',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${LexendDeca.variable} antialiased dark:bg-black dark:text-white mx-mx-page mt-mt-page `}
      >
        {children}
      </body>
    </html>
  );
}
